name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: MapLibre_Native_Ubuntu_24_04_x86_14_core
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"
      - name: NPM install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check formatting
        run: npm run format-check
